spring:
  application:
    name: library-crud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/book_db}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update